#!/usr/bin/env node
// Regenerates .vscode/tasks.json + .vscode/launch.json: a Build and a Play action for every example
// in examples/. Run `npm run vscode` after adding one. Both files are generated — edit this script,
// not them. Everything they invoke lives in scripts/rom.sh.
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const examples = fs
  .readdirSync(path.join(root, 'examples'), { withFileTypes: true })
  .filter((e) => e.isDirectory() && fs.existsSync(path.join(root, 'examples', e.name, 'package.json')))
  .map((e) => e.name)
  .sort();

const ROM = '${workspaceFolder}/scripts/rom.sh';
const banner = [
  'GENERATED by scripts/gen-vscode.js — run `npm run vscode` to refresh after adding an example.',
  'Play runs the ROM already on disk and never builds, so it starts instantly.',
];

// A shell task per action. `dedicated` panels keep a build and a running emulator from stealing each
// other's terminal, and Play stays open on failure so a "no ROM, build first" message can be read.
function task(name, action, target, extra = {}) {
  return {
    label: name,
    type: 'shell',
    command: `${ROM} ${action} ${target}`,
    options: { cwd: '${workspaceFolder}' },
    presentation: { reveal: 'always', panel: 'dedicated', clear: true, showReuseMessage: false },
    problemMatcher: action === 'build' ? ['$rustc'] : [],
    ...extra,
  };
}

const tasks = [
  // ${file} is the active editor's file; rom.sh maps it to its example (and falls back to the last
  // one when you are editing packages/*.tish, which is not in any example).
  task('Play: current example', 'play', '"${file}"', {
    group: { kind: 'test', isDefault: true },
    detail: 'Run the ROM for the example you are editing (no build)',
  }),
  task('Build: current example', 'build', '"${file}"', {
    group: { kind: 'build', isDefault: true },
    detail: 'tish build for the example you are editing',
  }),
  task('Play: pick example…', 'play', '"${input:example}"', { detail: 'Choose an example, run its ROM' }),
  task('Build: pick example…', 'build', '"${input:example}"', { detail: 'Choose an example, build it' }),
  task('Shot: current example', 'shot', '"${file}"', {
    detail: 'Headless screenshot -> examples/<name>/screenshot.png',
  }),
  ...examples.map((n) => task(`Play: ${n}`, 'play', n, { detail: `Run examples/${n} (no build)` })),
  ...examples.map((n) => task(`Build: ${n}`, 'build', n, { detail: `Build examples/${n}` })),
];

const input = {
  id: 'example',
  type: 'pickString',
  description: 'Which example?',
  options: examples,
  default: examples.includes('akari') ? 'akari' : examples[0],
};

write('tasks.json', { version: '2.0.0', tasks, inputs: [input] });

// Run & Debug entries: pick one from the dropdown and the green ▶ / F5 replays it. `node-terminal`
// is the built-in JS debugger's "just run this command" type — the only launch type that runs a
// shell command without a real debug adapter.
const launch = (name, action, target) => ({
  name,
  type: 'node-terminal',
  request: 'launch',
  command: `scripts/rom.sh ${action} ${target}`,
  cwd: '${workspaceFolder}',
});

write('launch.json', {
  version: '0.2.0',
  configurations: [
    launch('▶ Play current example', 'play', '"${file}"'),
    launch('▶ Play (pick example…)', 'play', '"${input:example}"'),
    ...examples.map((n) => launch(`▶ Play ${n}`, 'play', n)),
  ],
  inputs: [input],
});

function write(file, obj) {
  const dir = path.join(root, '.vscode');
  fs.mkdirSync(dir, { recursive: true });
  // VS Code parses these as jsonc, so the banner can be a real comment.
  const head = banner.map((l) => `// ${l}`).join('\n');
  fs.writeFileSync(path.join(dir, file), `${head}\n${JSON.stringify(obj, null, 2)}\n`);
  console.log(`wrote .vscode/${file} (${examples.length} examples)`);
}
