#!/usr/bin/env python3
"""Write `examples/creature-rpg/assets/theme.deck` — the overworld theme.

An eight-bar I-V-vi-IV loop in C, arranged for the GBA's four PSG voices with intensity stems, so
one playhead covers both walking around town and the lift when something is about to happen:

    layer 0   bass (wave) + chord pad (pulse 1)      the bed, always on
    layer 1   + melody (pulse 2)                     town
    layer 2   + drums (noise)                        an encounter is starting

That is the whole hardware budget — 2 pulse, 1 wave, 1 noise — and it is a HARD cap: deck layers
are mute gates, not extra voices, so a fifth track would be a compile error naming it. There is no
layer 3 here for that reason.

Bass lives on the wave channel because the square channels cannot sound below C2 (MIDI 36) and the
roots run down to F1.

Run from the repo root:  python3 scripts/gen_creature_music.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "examples", "creature-rpg", "assets", "theme.deck")

BPM = 132
BARS = 8

# I V vi IV | I V IV V — the progression, as (bass root, triad in the pad's octave).
PROG = [
    (36, (60, 64, 67)),   # C
    (31, (55, 59, 62)),   # G
    (33, (57, 60, 64)),   # Am
    (29, (53, 57, 60)),   # F
    (36, (60, 64, 67)),   # C
    (31, (55, 59, 62)),   # G
    (29, (53, 57, 60)),   # F
    (31, (55, 59, 62)),   # G
]

# The tune, as (midi, beat within the loop, duration in beats). Eight bars of four.
MELODY = [
    (64, 0, .75), (67, 1, .75), (72, 2, 1), (67, 3, 1),
    (71, 4, .75), (74, 5, .75), (71, 6, 1), (67, 7, 1),
    (69, 8, .75), (72, 9, .75), (76, 10, 1), (72, 11, 1),
    (74, 12, .75), (72, 13, .75), (69, 14, 2),
    (67, 16, .75), (72, 17, .75), (76, 18, 1), (72, 19, 1),
    (74, 20, .75), (71, 21, .75), (67, 22, 2),
    (65, 24, .75), (69, 25, .75), (72, 26, 1), (69, 27, 1),
    (71, 28, .75), (74, 29, .75), (79, 30, 2),
]


def note(midi, beat, dur, vel):
    return f"  note {midi} {beat:g} {dur:g} v {vel}"


def main():
    out = [
        "# CREATURE RPG — the overworld theme.",
        "#",
        "# GENERATED by scripts/gen_creature_music.py — edit the tables there, not here.",
        "#",
        "# Intensity stems share one playhead: 0 bass + pad, 1 + melody, 2 + drums. Raising the",
        "# intensity when an encounter starts lifts the arrangement without restarting the song.",
        "deck 1",
        f"bpm {BPM}",
        "",
        "track Bass id bass gen gameBoyDmg layer 0",
        "  gen type wave wave_shape saw vol 13",
    ]
    for bar, (root, _) in enumerate(PROG):
        b = bar * 4
        out += [note(root, b, .9, 110), note(root + 7, b + 1.5, .4, 80),
                note(root, b + 2, .9, 110), note(root + 7, b + 3.5, .4, 80)]

    out += ["", "track Pad id pad gen gameBoyDmg layer 0", "  gen type pulse duty 25 vol 6"]
    for bar, (_, triad) in enumerate(PROG):
        for e in range(8):                      # eighth-note arpeggio, up and back
            step = [0, 1, 2, 1][e % 4]
            out.append(note(triad[step], bar * 4 + e * .5, .45, 62))

    out += ["", "track Lead id lead gen gameBoyDmg layer 1", "  gen type pulse duty 50 vol 11"]
    for (m, b, d) in MELODY:
        out.append(note(m, b, d, 104))

    # One noise channel means the snare REPLACES the hat on its beat rather than sounding over it —
    # two notes at the same instant on one voice is not a thicker backbeat, it is a dropped hat.
    out += ["", "track Drums id drums gen gameBoyDmg layer 2",
            "  gen type noise noise_mode long vol 9"]
    for bar in range(BARS):
        for e in range(8):
            beat = bar * 4 + e * .5
            if e in (2, 6):
                out.append(note(58, beat, .25, 110))       # snare, beats 2 and 4
            else:
                out.append(note(76, beat, .12, 46))        # hat

    with open(OUT, "w") as f:
        f.write("\n".join(out) + "\n")
    notes = sum(1 for line in out if line.startswith("  note"))
    print(f"{OUT}\n  {BARS} bars @ {BPM}bpm, 4 tracks, {notes} notes, {os.path.getsize(OUT)} bytes")


if __name__ == "__main__":
    main()
