#!/usr/bin/env python3
"""Derive the glyph roster a `.strings` table needs, so the font baker bakes exactly those.

    python3 scripts/gen_strings_glyphs.py examples/polyglot

Reads every `assets/*.strings` in the example and writes `src/generated/glyphs.tish` containing the
sorted, unique, NON-ASCII characters those tables use — nothing else, and nothing hand-written.

## Why this is necessary

`font:` bakes a SELECTIVE glyph set, and that is the whole reason a CJK face fits on a cartridge.
The set comes from `collect_string_charset` in the tish compiler, which walks the program's **string
literals in the AST**. Its own doc comment names the gap:

> a non-ASCII char reachable only through a computed string is the rare gap
> (documented — add it to a literal if needed)

A `.strings` table is exactly that case: the text is data, so the compiler never sees it, and every
non-ASCII character renders as a blank gap. Verified across four fonts — `ark-pixel-10px`,
`ark-pixel-10px-cjk`, `m5x7`, `monogram` — identical gap in all four, so it is not font-specific.

## Why a generator rather than a hand-written list

Because a hand-written list is not selective baking, it is a second copy of the content that drifts
the moment somebody adds a translation — and it fails silently and only in the language nobody
reviewing can read. **The roster is DERIVED from the tables**, every time, and this script is the
only thing that writes it.

The alternative fix is to teach `collect_string_charset` to read scheme files that opt in. That lives
in the tish compiler, and core tish is deliberately not modified from this repo (`ad68e6388`), so it
would have to be proposed upstream. Until then this keeps the automation intact and the roster
honest.
"""
from __future__ import annotations

import pathlib
import sys

HEADER = """// GENERATED by scripts/gen_strings_glyphs.py — DO NOT EDIT.
//
// Every NON-ASCII character used by this example's `.strings` tables, as one string literal.
//
// ⚠️ IT EXISTS ONLY TO BE SEEN BY THE COMPILER. `font:` bakes a selective glyph set collected from
// the program's string LITERALS; a `.strings` table is data, so its characters are invisible to that
// pass and would render as blank gaps. Referencing this constant once puts them in the AST, and the
// font baker then bakes exactly these glyphs and no others — which is the point: the roster is
// derived from the tables, never hand-written, so it cannot drift when a translation is added.
//
// Regenerate with:  python3 scripts/gen_strings_glyphs.py examples/{name}
"""


def collect(example: pathlib.Path) -> tuple[set[str], list[pathlib.Path]]:
    files = sorted((example / "assets").glob("*.strings"))
    chars: set[str] = set()
    for f in files:
        for line in f.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            # Skip comments and [lang] headers: neither is ever drawn.
            if not line or line.startswith("#"):
                continue
            if line.startswith("[") and line.endswith("]"):
                continue
            for ch in line:
                if ord(ch) >= 0x7F:
                    chars.add(ch)
    return chars, files


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    root = pathlib.Path(__file__).resolve().parent.parent
    example = (root / sys.argv[1]) if not pathlib.Path(sys.argv[1]).is_absolute() else pathlib.Path(sys.argv[1])
    example = example.resolve()
    if not (example / "assets").is_dir():
        print(f"no assets/ in {example}", file=sys.stderr)
        return 1

    chars, files = collect(example)
    if not files:
        print(f"no .strings files in {example}/assets", file=sys.stderr)
        return 1

    out_dir = example / "src" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    roster = "".join(sorted(chars))
    # A tish string literal: escape only what would break it.
    escaped = roster.replace("\\", "\\\\").replace('"', '\\"')
    body = HEADER.replace("{name}", example.name)
    body += f'export let STRING_GLYPHS = "{escaped}"\n'
    (out_dir / "glyphs.tish").write_text(body, encoding="utf-8")

    names = ", ".join(f.name for f in files)
    if roster:
        print(f"  glyphs.tish  {len(chars)} non-ASCII glyph(s) from {names}: {roster}")
    else:
        print(f"  glyphs.tish  no non-ASCII characters in {names} — roster is empty (ASCII is always baked)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
