#!/usr/bin/env python3
"""Generate examples/bench-tables/src/tables.tish.

The bench needs the SAME 2,304 values reachable two ways — as a module-level array literal (which
the compiler promotes to a Rust `static`) and as an array built with `push()` in a loop (which stays
a `VmRef<Vec<i32>>`). Authoring them by hand would let them drift, and a bench whose two arms hold
different data measures nothing; so both are emitted from one list here, and the ROM checksums them
against each other at boot.

2,304 = 18 x 128, which is the shape of the topdown RPG port's generated dungeon-room table (two
quests x nine levels x 128 rooms). The bench is about that file.

    python3 scripts/gen_bench_tables.py
"""

import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent / "examples/bench-tables/src/tables.tish"

N = 2304
STRIDE = 128
# A power-of-two mask that cannot change what any fill reads (every fill index stays well under it),
# so `warmFillMask` and `warmFill` differ in the index EXPRESSION and in nothing else.
MASK = 2047

# Deterministic, non-trivial, and every value distinct enough that a checksum catches a shifted or
# truncated arm. Kept under 256 so the literal stays narrow and the file stays readable.
VALUES = [(i * 37 + (i >> 5)) & 255 for i in range(N)]


def wrap(values, per_line=32, indent=" " * 22):
    rows = []
    for i in range(0, len(values), per_line):
        rows.append(", ".join(str(v) for v in values[i:i + per_line]))
    return (",\n" + indent).join(rows)


HEADER = f'''// GENERATED by scripts/gen_bench_tables.py — do not edit.
//
// The same {N} values, authored two ways. That is the entire experiment: `LIT` is a module-level
// array LITERAL, which the tish compiler promotes to a Rust `static`; `PUSH` is built with `push()`
// in a loop, which stays a `VmRef<Vec<i32>>`. Identical contents, identical indices, identical
// loops — only the way the array was written differs.
//
// ⚠️ The two arms MUST hold the same data or the comparison is meaningless, so `tablesChecksum()`
// exists and `main.tish` refuses to report a measurement unless both arms agree.

let STRIDE: i32 = {STRIDE}

export let LIT: i32[] = [{{LIT}}]

export let PUSH: i32[] = []
let pi: i32 = 0
while (pi < {N}) {{ PUSH.push(LIT[pi]); pi = pi + 1 }}

// ── The boxed-accessor shape ──────────────────────────────────────────────────────────────────
//
// The topdown RPG port's world module reads its room tables through `uwDoor(roomId, side)`, which calls
// `uwIndex(roomId)`, which reads the module scalars `quest` and `curLevel`. Touching module state is
// what makes a tish function ineligible for typed lowering (tishlang/tish#647), so every one of that
// file's nineteen accessors is a boxed `value_call`. These two reproduce it exactly — same shape,
// same reason — over each arm, so the bench can tell the COST OF THE ARRAY apart from the COST OF
// THE ACCESSOR. They were confounded for as long as nobody separated them.

let level: i32 = 3

export function setLevel(v: i32) {{ level = v }}

function idx(k: i32): i32 {{ return (level - 1) * STRIDE + (k & (STRIDE - 1)) }}

export function litAt(k: i32): i32 {{ return LIT[idx(k)] }}
export function pushAt(k: i32): i32 {{ return PUSH[idx(k)] }}

// ── The warmed slice ──────────────────────────────────────────────────────────────────────────
//
// The pattern copies the slice an attacker actually needs out of a
// promoted static into a pushed array once, then reads that. This is the same move, at the same
// width, so the bench can price both the warmed READ and the FILL that pays for it.

export let WARM: i32[] = []
let wi: i32 = 0
while (wi < STRIDE) {{ WARM.push(0); wi = wi + 1 }}

/// Copy `n` elements of `LIT` at `base` into `WARM`. `n` is a parameter so the bench can measure a
/// SHORT fill and scale it: a full {STRIDE}-element fill out of a boxed literal would overrun a
/// frame, and a span that overruns a frame wraps the 16-bit timer and reports fiction.
export function warmFill(base: i32, n: i32) {{
  let i: i32 = 0
  while (i < n) {{ WARM[i] = LIT[base + i]; i = i + 1 }}
}}

// ── Decomposing the fill ──────────────────────────────────────────────────────────────────────
//
// `warmFill` measured ~25 ticks an element, against a LIT read of ~0.45 and a PUSH read of ~1.55.
// That is 50x the parts it is made of, so one of three things is expensive and guessing which is
// how a wrong number gets written into a doc. These isolate it:
//
//   warmFillConst   the WRITE alone, no source array
//   warmFillPush    the same write, source is the PUSHED arm
//   warmFillMask    the same write, source is the LITERAL, indexed with a MASK
//   warmFill        the same write, source is the LITERAL, indexed with an ADD   (above)
//
// The suspect is the INDEX EXPRESSION, not the arrays. Every fast read in this file is `arr[k & M]`
// — a mask. A fill reads `LIT[base + i]`, an add against a parameter. bench-access recorded that
// hoisting an index into a local did not help because the boxing lived in the promoted array's read
// path; if tishlang/tish#645's fix reaches masked indices but not computed ones, that is a live bug
// and these spans are what shows it.

export function warmFillConst(base: i32, n: i32) {{
  let i: i32 = 0
  while (i < n) {{ WARM[i] = base + i; i = i + 1 }}
}}

export function warmFillPush(base: i32, n: i32) {{
  let i: i32 = 0
  while (i < n) {{ WARM[i] = PUSH[base + i]; i = i + 1 }}
}}

export function warmFillMask(base: i32, n: i32) {{
  let i: i32 = 0
  while (i < n) {{ WARM[i] = LIT[(base + i) & {MASK}]; i = i + 1 }}
}}

/// Both arms, summed independently. Equal sums mean the arms agree; `main.tish` gates on it.
export function tablesChecksum(arm: i32): i32 {{
  let acc: i32 = 0
  let i: i32 = 0
  if (arm === 0) {{ while (i < {N}) {{ acc = acc + LIT[i]; i = i + 1 }} }}
  else {{ while (i < {N}) {{ acc = acc + PUSH[i]; i = i + 1 }} }}
  return acc
}}
'''


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER.replace("{LIT}", wrap(VALUES)).replace("{MASK}", str(MASK)))
    print(f"wrote {OUT} ({N} values, checksum {sum(VALUES)})")


if __name__ == "__main__":
    main()
