#!/usr/bin/env python3
"""Generate placeholder art + level data for the side-scrolling platformer examples.

Outputs, into each example's dir:
  assets/tileset.png   a 5-tile 16px strip (sky, grass, dirt, brick, platform) for `background:`
  assets/hero.png      a 4-frame 16x16 side-facing character sheet for `sheet:`
  src/maps.tish        the level as Tiled-shaped stream-map data (loadStreamMap)

The camera behaviour is the point of these examples, so the art is deliberately simple.
"""
import os
from PIL import Image, ImageDraw

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# ── tileset: 5 tiles, GID = index+1 (1 sky, 2 grass, 3 dirt, 4 brick, 5 platform) ──
SKY, GRASS, DIRT, BRICK, PLAT = 1, 2, 3, 4, 5
SOLID = [GRASS, DIRT, BRICK, PLAT]


def make_tileset():
    im = Image.new("RGBA", (16 * 5, 16), (0, 0, 0, 0))
    d = ImageDraw.Draw(im)

    def cell(i):
        return i * 16

    # sky
    d.rectangle([cell(0), 0, cell(0) + 15, 15], fill=(122, 190, 246))
    # grass: green cap over brown
    d.rectangle([cell(1), 0, cell(1) + 15, 15], fill=(120, 78, 44))
    d.rectangle([cell(1), 0, cell(1) + 15, 4], fill=(88, 176, 80))
    d.rectangle([cell(1), 5, cell(1) + 15, 6], fill=(64, 132, 58))
    # dirt: brown with speckle
    d.rectangle([cell(2), 0, cell(2) + 15, 15], fill=(120, 78, 44))
    for (x, y) in [(3, 3), (9, 6), (6, 11), (12, 13), (2, 9)]:
        d.point((cell(2) + x, y), fill=(96, 60, 32))
    # brick: grey blocks with mortar lines
    d.rectangle([cell(3), 0, cell(3) + 15, 15], fill=(122, 122, 132))
    for y in (0, 8):
        d.line([cell(3), y, cell(3) + 15, y], fill=(80, 80, 90))
    d.line([cell(3) + 8, 0, cell(3) + 8, 7], fill=(80, 80, 90))
    d.line([cell(3), 8, cell(3), 15], fill=(80, 80, 90))
    d.line([cell(3) + 4, 8, cell(3) + 4, 15], fill=(80, 80, 90))
    # platform: wooden plank block (fully opaque — the `background:` bake needs every tile
    # opaque; the empty cells above/below come from GID 0, not tile transparency)
    d.rectangle([cell(4), 0, cell(4) + 15, 15], fill=(120, 82, 44))
    d.rectangle([cell(4), 0, cell(4) + 15, 4], fill=(168, 120, 66))
    d.rectangle([cell(4), 0, cell(4) + 15, 1], fill=(198, 150, 92))
    d.line([cell(4), 8, cell(4) + 15, 8], fill=(96, 64, 34))
    return im


def make_hero():
    """4 frames (idle, run-a, run-b, jump), 16x16, facing right."""
    SKIN, SHIRT, PANTS, HAIR = (245, 205, 160), (60, 120, 210), (40, 44, 60), (70, 46, 30)
    sheet = Image.new("RGBA", (16 * 4, 16), (0, 0, 0, 0))

    def draw(fx, legs):
        im = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
        d = ImageDraw.Draw(im)
        d.rectangle([5, 1, 11, 5], fill=HAIR)         # hair
        d.rectangle([6, 3, 11, 7], fill=SKIN)         # face (facing right)
        d.rectangle([11, 4, 12, 5], fill=(20, 20, 20))  # eye
        d.rectangle([5, 7, 11, 12], fill=SHIRT)       # torso
        d.rectangle([11, 8, 12, 11], fill=SKIN)       # front arm
        for (x0, x1, y0, y1) in legs:                 # legs
            d.rectangle([x0, y0, x1, y1], fill=PANTS)
        sheet.paste(im, (fx * 16, 0))

    stand = [(6, 8, 12, 15), (9, 11, 12, 15)]
    run_a = [(4, 6, 12, 15), (10, 12, 12, 14)]
    run_b = [(6, 8, 12, 14), (9, 11, 12, 15)]
    jump = [(5, 7, 11, 14), (10, 12, 11, 14)]
    draw(0, stand)
    draw(1, run_a)
    draw(2, run_b)
    draw(3, jump)
    return sheet


# ── ASCII levels → GID grid ────────────────────────────────────────────────────
#   '.' sky   '#' ground (auto grass-topped)   '=' platform   'B' brick   '@' spawn
def parse_level(rows):
    h = len(rows)
    w = max(len(r) for r in rows)
    rows = [r.ljust(w, ".") for r in rows]
    solid_char = set("#=B")
    gid = [[SKY] * w for _ in range(h)]
    spawn = (2, h - 3)
    for y in range(h):
        for x in range(w):
            ch = rows[y][x]
            if ch == "@":
                spawn = (x, y)
            elif ch == "#":
                above = rows[y - 1][x] if y > 0 else "."
                gid[y][x] = GRASS if above not in solid_char else DIRT
            elif ch == "=":
                gid[y][x] = PLAT
            elif ch == "B":
                gid[y][x] = BRICK
    flat = [gid[y][x] for y in range(h) for x in range(w)]
    return w, h, flat, spawn


def emit_maps_tish(path, name, w, h, data, spawn):
    rowstrs = []
    for y in range(h):
        row = ", ".join(str(data[y * w + x]) for x in range(w))
        rowstrs.append("      " + row + ("," if y < h - 1 else ""))
    body = "\n".join(rowstrs)
    solid = ", ".join(str(s) for s in SOLID)
    txt = f"""// Generated by scripts/gen_platformer.py — a side-scrolling platformer level as
// Tiled-shaped stream-map data. GIDs: 1 sky, 2 grass, 3 dirt, 4 brick, 5 platform.
// Spawn tile: ({spawn[0]}, {spawn[1]}).
export const {name} = {{
  width: {w}, height: {h}, tileSize: 16, tilesetCols: 5,
  spawnCol: {spawn[0]}, spawnRow: {spawn[1]},
  solid: [{solid}],
  layers: [
    {{ priority: 2, data: [
{body}
    ] }}
  ]
}}
"""
    with open(path, "w") as f:
        f.write(txt)


# Scroll example: one wide level, camera follows the player horizontally.
SCROLL_LEVEL = [
    "................................................",
    "................................................",
    "................................................",
    "..........=====.................=====...........",
    "................................................",
    ".....=====...........====.......................",
    "................................=====...........",
    "............................BB..................",
    "..............====.........BBB.......====.......",
    "...@.....................BBBB...................",
    "......................BBBBB......................",
    "#######......########........###################",
    "#######......########........###################",
]

# Rooms example: a 2x2 grid of 15x10-tile rooms; the camera locks per room and slides on cross.
ROOMS_LEVEL = [
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",  # 0  ceiling
    "B............................B",  # 1
    "B...@........................B",  # 2
    "B..........====.....===......B",  # 3
    "B...................===......B",  # 4
    "B......====.................=B",  # 5
    "B..........................==B",  # 6
    "B.....===........===........=B",  # 7
    "B..........................==B",  # 8
    "#########......###############",  # 9  floor of the top rooms (gap = drop to bottom)
    "B............................B",  # 10
    "B..........===...............B",  # 11
    "B......===..............===..B",  # 12
    "B...........................=B",  # 13
    "B.....===.......====........=B",  # 14
    "B...........................=B",  # 15
    "B..===...............===.....B",  # 16
    "B............................B",  # 17
    "B............................B",  # 18
    "##############################",  # 19 bottom floor
]


def write_example(subdir, level, name):
    ex = os.path.join(REPO, "examples", subdir)
    os.makedirs(os.path.join(ex, "assets"), exist_ok=True)
    os.makedirs(os.path.join(ex, "src"), exist_ok=True)
    make_tileset().save(os.path.join(ex, "assets", "tileset.png"))
    make_hero().save(os.path.join(ex, "assets", "hero.png"))
    w, h, data, spawn = parse_level(level)
    emit_maps_tish(os.path.join(ex, "src", "maps.tish"), name, w, h, data, spawn)
    print(f"{subdir}: {w}x{h} tiles, spawn {spawn}")


if __name__ == "__main__":
    write_example("platformer-scroll", SCROLL_LEVEL, "level")
    write_example("platformer-rooms", ROOMS_LEVEL, "level")
    print("done")
