#!/usr/bin/env python3
"""Generate examples/kart-circuit/assets/race.deck — the race theme.

Run from the repo root:  python3 scripts/gen_kart_circuit_music.py

A sixteen-bar loop in A minor at 152 BPM, written as INTENSITY STEMS so the
same playhead can carry the whole game:

    layer 0   bass (wave)                 always on — the bed
    layer 1   lead (pulse 1)              the tune; title screen and up
    layer 2   kick (PCM) + hats (noise)   the race
    layer 3   stabs (pulse 2)             the final lap

`deckSetIntensity` is a mute gate on stems that are already running, not a
restart, so raising it on the last lap lifts the arrangement without the music
skipping — which is the whole reason the final lap gets stabs rather than a
different song.

Channel budget (hard caps, overflow is a bake error): 2 pulse, 1 wave, 1 noise,
2 PCM.  This uses 2 pulse + 1 wave + 1 noise + 1 PCM, so it is exactly full on
the PSG side with one PCM voice spare for sound effects.
"""

import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "examples", "kart-circuit", "assets", "race.deck")

BPM = 152
BARS = 16
BEATS = BARS * 4

# A minor, the obvious key for something that wants to sound quick and a bit
# tense.  One chord per bar; the four-bar cycle repeats with the melody moving
# over it, which is enough shape for a loop nobody is meant to notice looping.
#            i     VI    III   VII
CHORDS = [
    (57, [57, 60, 64]),   # Am
    (53, [53, 57, 60]),   # F
    (48, [48, 52, 55]),   # C
    (55, [55, 59, 62]),   # G
]

# The tune, as scale-degree offsets into the bar's chord plus passing notes.
# Written out rather than generated randomly: a racing theme wants a hook you
# recognise on the second lap.
LEAD = [
    # (beat within the 4-bar phrase, chord-tone index, octave shift, duration)
    (0.0, 2, 1, 0.5), (0.5, 1, 1, 0.5), (1.0, 0, 1, 0.5), (1.5, 1, 1, 0.5),
    (2.0, 2, 1, 0.75), (3.0, 1, 1, 0.5), (3.5, 2, 1, 0.5),
    (4.0, 1, 1, 0.5), (4.5, 2, 1, 0.5), (5.0, 1, 1, 1.0),
    (6.0, 0, 1, 0.5), (6.5, 2, 0, 0.5), (7.0, 1, 1, 1.0),
    (8.0, 0, 1, 0.5), (8.5, 1, 1, 0.5), (9.0, 2, 1, 0.5), (9.5, 1, 1, 0.5),
    (10.0, 2, 1, 1.5), (11.5, 1, 1, 0.5),
    (12.0, 2, 1, 0.5), (12.5, 1, 1, 0.5), (13.0, 0, 1, 1.0),
    (14.0, 1, 1, 0.5), (14.5, 2, 1, 0.5), (15.0, 0, 1, 1.0),
]


def lines():
    out = []
    out.append("# KART CIRCUIT — the race theme.")
    out.append("#")
    out.append("# GENERATED by scripts/gen_kart_circuit_music.py — edit the tables there, not here.")
    out.append("#")
    out.append("# Intensity stems: 0 bass · 1 + lead · 2 + drums · 3 + stabs. All one playhead, so")
    out.append("# raising the intensity on the final lap lifts the arrangement without a skip.")
    out.append("deck 1")
    out.append(f"bpm {BPM}")
    out.append("")

    # ── Bass: wave channel, because square cannot go below C2 and this wants to
    #    sit under everything. Driving eighths with an octave lift on the &.
    out.append("track Bass id bass gen gameBoyDmg layer 0")
    out.append("  gen type wave wave_shape saw vol 14")
    for bar in range(BARS):
        root, _ = CHORDS[bar % 4]
        low = root - 24
        for eighth in range(8):
            beat = bar * 4 + eighth * 0.5
            pitch = low if eighth % 2 == 0 else low + 12
            vel = 112 if eighth % 2 == 0 else 84
            out.append(f"  note {pitch} {beat:g} 0.45 v {vel}")
    out.append("")

    # ── Pad, also layer 0 — held chord tones an octave up, so the bed is not just
    #    a bass line. Shares the wave channel by never overlapping the bass? It
    #    cannot: one wave voice. So the pad rides the SECOND pulse at low volume
    #    and is promoted to stabs at intensity 3 by a separate track.
    out.append("track Lead id lead gen gameBoyDmg layer 1")
    out.append("  gen type pulse duty 50 env_mode adsr vol 12")
    out.append("  gen attack 0 decay 0.10 sustain 10 release 0.08")
    for rep in range(BARS // 4):
        base = rep * 16
        for beat, tone, oct_shift, dur in LEAD:
            bar = int((base + beat) // 4)
            _, tones = CHORDS[bar % 4]
            pitch = tones[tone % len(tones)] + 12 * oct_shift
            # Second half of the loop lifts a fifth for a bit of lift.
            if rep >= 2:
                pitch += 7 if (rep == 3 and beat >= 8) else 0
            out.append(f"  note {pitch} {base + beat:g} {dur:g} v 108")
    out.append("")

    # ── Drums. One noise voice does hats and snare; the kick is a PCM voice with
    #    a pitch drop, which is the standard trick for a kick without a sample.
    out.append("track Kick id kick gen gbaDirectSound layer 2")
    out.append("  gen waveform sine vol 15 pitch_drop -18 pitch_dec 0.05")
    out.append("  gen attack 0 decay 0.09 sustain 0 release 0.02")
    for bar in range(BARS):
        for beat in (0.0, 1.5, 2.0, 3.5):
            out.append(f"  note 40 {bar * 4 + beat:g} 0.2 v 122")
    out.append("")

    out.append("track Hats id hats gen gameBoyDmg layer 2")
    out.append("  gen type noise noise_mode short vol 6")
    out.append("  gen env_mode adsr attack 0 decay 0.035 sustain 0 release 0.02")
    for bar in range(BARS):
        for i in range(8):
            beat = bar * 4 + i * 0.5
            # Backbeat snare on 2 and 4 — louder, longer noise.
            if i in (2, 6):
                out.append(f"  note 62 {beat:g} 0.14 v 104")
            else:
                out.append(f"  note 74 {beat:g} 0.08 v 52")
    out.append("")

    # ── Stabs, layer 3: the final lap. Offbeat chord hits on the second pulse.
    out.append("track Stabs id stabs gen gameBoyDmg layer 3")
    out.append("  gen type pulse duty 25 env_mode adsr vol 10")
    out.append("  gen attack 0 decay 0.07 sustain 4 release 0.05")
    for bar in range(BARS):
        _, tones = CHORDS[bar % 4]
        for i, beat in enumerate((0.75, 1.75, 2.75, 3.75)):
            pitch = tones[i % len(tones)] + 12
            out.append(f"  note {pitch} {bar * 4 + beat:g} 0.22 v 92")
    return out


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    text = "\n".join(lines()) + "\n"
    with open(OUT, "w") as f:
        f.write(text)
    notes = sum(1 for l in text.splitlines() if l.strip().startswith("note "))
    secs = BEATS * 60.0 / BPM
    print(f"race.deck  {BARS} bars at {BPM} bpm = {secs:.1f}s loop, {notes} notes")
    print("  stems: 0 bass · 1 lead · 2 kick+hats · 3 stabs")
    print("  channels: 2 pulse (lead, stabs) + 1 wave (bass) + 1 noise (hats) + 1 PCM (kick)")


if __name__ == "__main__":
    main()
