#!/usr/bin/env python3
"""Generate examples/warheads' lookup tables as typed tish literals.

The artillery spike's tables (scripts/gen_artillery_tables.py) with ONE change: warheads plays on a
512x384 arena rather than a 240x160 screen, so GACC's coarse half has to reach further.

⚠️ WHY THE COARSE SHIFT MOVED FROM 8 TO 9. The runtime indexes GACC by a two-slope compression of d^2
and clamps the coarse bucket at 1023. With `d2 >> 8` that clamp lands at d = 512 — shorter than this
arena's 640 px diagonal, so a shell in one corner would be pulled by a planet in the other as though
it were 512 px away rather than 640. Not a crash, and easy to never notice: it is a slightly
too-strong far field, on the shots that travel furthest. `d2 >> 9` reaches d = 724 and covers the
whole board.

Everything else — the constant, the near clamp, the fine half — is unchanged from the spike, because
the spike measured it and it felt right.

    python3 scripts/gen_warheads_tables.py
"""

import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "examples/warheads/src/tables.tish"

C = 3_000_000_000          # tuned in the artillery spike; see its audit block
DMIN = 6.0                 # the near-field clamp, held IN THE TABLE so the loop needs no branch

GACC_N = 2048
FINE_SPLIT = 4096          # d2 below this uses the fine half
COARSE_SHIFT = 9           # ⚠️ 9, not the spike's 8 — see the module docstring

# |dx| can reach the arena width plus the escape margin (512 + 240 = 752), and the runtime masks with
# & 1023, so anything past 1023 would ALIAS a far offset onto a near one — a planet across the board
# yanking the shell, which looks like physics and is masking.
SQ_N = 1024
ISQRT_N = 2048             # blast falloff; the widest blast radius is 40


def d_of(i):
    """The distance a GACC index stands for — the inverse of the runtime's compression."""
    if i < GACC_N // 2:
        d2 = i * 4 + 2
    else:
        d2 = (i - GACC_N // 2) * (1 << COARSE_SHIFT) + (1 << (COARSE_SHIFT - 1))
    return math.sqrt(max(d2, 1.0))


def rows(name, vals, per):
    """`export let NAME: i32[] = [...]` — never `const`, never unannotated.

    A `const`, or a `let` with no type, is a boxed Value::Array of boxed f64 at 28 bytes an element.
    The annotated `let` is promoted to a Rust `const [i32; N]`: a 0.45-tick ROM load.
    """
    out = [f"export let {name}: i32[] = ["]
    for i in range(0, len(vals), per):
        out.append("  " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
    out[-1] = out[-1].rstrip(",")
    out.append("]")
    return "\n".join(out)


def main():
    gacc = [int(round(C / max(d_of(i), DMIN) ** 3)) for i in range(GACC_N)]
    sq = [i * i for i in range(SQ_N)]
    isqrt = [int(round(math.sqrt(i))) for i in range(ISQRT_N)]
    sint = [int(round(256 * math.sin(2 * math.pi * a / 256))) for a in range(256)]
    cost = [int(round(256 * math.cos(2 * math.pi * a / 256))) for a in range(256)]

    # Overflow audit for `imul(imul(dx, k) >> 10, mass) >> 8`. |dx| <= d always, so imul(dx,k) peaks
    # at C/d^2 — maximised at the near clamp.
    peak = max(int(d_of(i) * gacc[i]) for i in range(GACC_N))
    peak2 = (peak >> 10) * 1024
    assert peak < 2**31, f"imul(dx,k) overflows i32: {peak}"
    assert peak2 < 2**31, f"imul(.,mass) overflows i32: {peak2}"

    reach = d_of(GACC_N - 1)
    assert reach > 640, f"coarse half only reaches d={reach:.0f}, short of the 640 px diagonal"

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"""// GENERATED by scripts/gen_warheads_tables.py — do not edit.
//
// Lookup tables standing in for arithmetic the ARM7TDMI cannot do cheaply: it has no FPU and no
// divide instruction, so `dx * dx` between two i32 locals is a soft-float multiply and `C / d^3` is
// a software division per planet per substep.
//
// ⚠️ EVERY READ MUST MASK ITS INDEX, AND EVERY TABLE IS A POWER OF TWO LONG. Both halves matter: the
// identical promoted array costs 0.45 ticks through a mask the compiler can prove in bounds and 25
// through anything else, and the f64 fallback it emits otherwise is CONTAGIOUS — it poisons the type
// of every expression it feeds. Measured in examples/artillery's own generated Rust.

// d^2 for |d| < {SQ_N}. Replaces `dx * dx`.
{rows('SQ', sq, 16)}

// C / d^3, C = {C:,}, clamped at d >= {DMIN:g}. Index: `d2 < {FINE_SPLIT}` -> `d2 >> 2`,
// else `{GACC_N // 2} | (d2 >> {COARSE_SHIFT})`. Reaches d = {reach:.0f}, past the 640 px diagonal.
{rows('GACC', gacc, 8)}

// round(sqrt(i)) for i < {ISQRT_N}. Blast falloff is linear in distance, so it needs a real root.
{rows('ISQRT', isqrt, 24)}

// sin and cos in Q8 (256 = 1.0) over 256 angle units per turn — a turn, not 360 degrees, so an
// angle indexes these with a bare mask and never a division.
{rows('SINT', sint, 16)}

{rows('COST', cost, 16)}
""")

    def accel_px(d, mass_q8):
        dd = int(d * d)
        i = (dd >> 2) if dd < FINE_SPLIT else (GACC_N // 2 | (dd >> COARSE_SHIFT))
        return ((((int(d) * gacc[min(i, GACC_N - 1)]) >> 10) * mass_q8) >> 8) / 65536.0

    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"  ROM: {(GACC_N + SQ_N + ISQRT_N + 512) * 4 / 1024:.1f} KB   coarse half reaches d={reach:.0f}")
    print(f"  overflow headroom {2**31 / peak:.1f}x")
    print("\n  planet class        surface a    a @80px   a @200px   escape v")
    print("  " + "-" * 60)
    for name, r, mass in (("SMALL  r14 m256", 14, 256), ("MED    r20 m448", 20, 448),
                          ("LARGE  r26 m704", 26, 704), ("GIANT  r30 m960", 30, 960)):
        gm = C * mass / float(1 << 34)
        print(f"  {name}   {accel_px(r + 2, mass):8.3f}   {accel_px(80, mass):8.4f}   "
              f"{accel_px(200, mass):8.5f}   {math.sqrt(2 * gm / (r + 2)):7.2f}")
    print("\n  A shot crosses this arena in roughly 150-250 ticks, so `a @80px` is the column that")
    print("  decides whether a well is worth flying around. Escape v is where a planet CAPTURES.")


if __name__ == "__main__":
    main()
