#!/usr/bin/env python3
"""ninja_autotile.py — autotile a terrain grid using the NinjaAdventure tileset autotile
tables captured in assets/ninja-adventure/catalog/autotile.json.

NinjaAdventure terrains are Godot "match corners and sides" (47-blob): each autotile tile
carries an 8-way peering mask [top_left, top, top_right, left, right, bottom_left, bottom,
bottom_right] where 1 means "same terrain on that side/corner". A corner bit is only meaningful
when BOTH its adjacent sides are also same-terrain (the 47-case reduction) — verified true for
the shipped tables. To paint a map, we compute each cell's neighbour mask under that reduction
and pick the tile whose mask matches.

Library:
    at = Autotiler("assets/ninja-adventure/catalog/autotile.json")
    at.materials("TilesetFloor.png")   # dirt_grass, … (see autotile.json / index.json)
    gids = at.terrain_to_gids(grid, w, h, "TilesetFloor.png", "snow", fill=1, oob_same=True)
        grid     : row-major list[int]; cells == `fill` get painted with `material`'s autotile
        material : named material of the tileset (47-blob, 3x3 island, or wall/carpet frame)
        returns  : row-major list[int] of gids (0 = empty; N -> tileset tile N-1)

Derived materials (Hole/Water/Field/Interior/…) are regenerated by scripts/gen_autotile_masks.py;
Tiled wangsets by scripts/gen_tileset_library.py.

CLI (self-test + preview):
    python3 scripts/ninja_autotile.py --demo TilesetFloor.png out.png [material]
      paints a blob-shaped patch of the material and renders it, to eyeball edges/corners.
"""
import json, os, sys

# mask index order, matching catalog/autotile.json "bit_order"
TL, T, TR, L, R, BL, B, BR = range(8)


class Autotiler:
    def __init__(self, catalog_path):
        self.data = json.load(open(catalog_path))
        self.tilesets = self.data["tilesets"]
        # per (tileset, material): {mask_tuple: [gid, ...variants]}
        self._lut = {}
        for name, ts in self.tilesets.items():
            for mat, m in ts["materials"].items():
                lut = {}
                for t in m["tiles"]:
                    lut.setdefault(tuple(t["mask"]), []).append(t["gid"])
                self._lut[(name, mat)] = lut

    def cols(self, tileset):
        return self.tilesets[tileset]["cols"]

    def materials(self, tileset):
        return list(self.tilesets[tileset]["materials"].keys())

    def _mask(self, grid, w, h, c, r, fill, oob_same):
        """8-way same-terrain mask with Godot corner reduction."""
        def same(cc, rr):
            if cc < 0 or cc >= w or rr < 0 or rr >= h:
                return oob_same
            return grid[rr * w + cc] == fill
        top, bot = same(c, r - 1), same(c, r + 1)
        left, right = same(c - 1, r), same(c + 1, r)
        m = [0] * 8
        m[T], m[B], m[L], m[R] = int(top), int(bot), int(left), int(right)
        # a corner counts only when both adjacent sides are also same-terrain
        m[TL] = int(same(c - 1, r - 1) and top and left)
        m[TR] = int(same(c + 1, r - 1) and top and right)
        m[BL] = int(same(c - 1, r + 1) and bot and left)
        m[BR] = int(same(c + 1, r + 1) and bot and right)
        return tuple(m)

    def terrain_to_gids(self, grid, w, h, tileset, material, fill=1, oob_same=True):
        """Paint every cell of `grid` equal to `fill` with `material`'s autotile from `tileset`."""
        lut = self._lut[(tileset, material)]
        keys = list(lut.keys())
        out = [0] * (w * h)
        for r in range(h):
            for c in range(w):
                if grid[r * w + c] != fill:
                    continue
                mask = self._mask(grid, w, h, c, r, fill, oob_same)
                variants = lut.get(mask)
                if variants is None and keys:
                    # nearest-mask fallback (robustness for partial tables)
                    best = min(keys, key=lambda k: sum(a != b for a, b in zip(k, mask)))
                    variants = lut[best]
                if variants:
                    # deterministic variant pick (spatial hash) for subtle variety
                    out[r * w + c] = variants[(c * 7 + r * 13) % len(variants)]
        return out

    def coverage(self, tileset, material):
        """How complete is this material's 47-blob table? (47 = full)."""
        return len(self._lut.get((tileset, material), {}))


# ---- CLI self-test / preview -------------------------------------------------
def _demo(tileset, out_png, material="dirt_grass"):
    from PIL import Image
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    at = Autotiler(os.path.join(root, "assets/ninja-adventure/catalog/autotile.json"))
    print(f"{tileset}/{material}: 47-blob coverage = {at.coverage(tileset, material)}/47 masks "
          f"(materials: {', '.join(at.materials(tileset))})")
    W, H = 12, 10
    grid = [0] * (W * H)
    # carve a lumpy dirt patch (terrain 1) to exercise edges + inner corners
    patch = [(3, 2), (4, 2), (5, 2), (6, 2), (7, 2),
             (3, 3), (4, 3), (5, 3), (6, 3), (7, 3), (8, 3),
             (3, 4), (4, 4), (6, 4), (7, 4), (8, 4),
             (3, 5), (4, 5), (5, 5), (6, 5), (7, 5), (8, 5),
             (4, 6), (5, 6), (6, 6), (7, 6)]
    for c, r in patch:
        grid[r * W + c] = 1
    gids = at.terrain_to_gids(grid, W, H, tileset, material, fill=1, oob_same=False)
    # render: grass base (a plain grass tile) + autotiled dirt overlay
    cols = at.cols(tileset)
    atlas = Image.open(os.path.join(root, "assets/ninja-adventure/Backgrounds/Tilesets", tileset)).convert("RGBA")

    def tile(gid):
        tid = gid - 1
        sx, sy = (tid % cols) * 16, (tid // cols) * 16
        return atlas.crop((sx, sy, sx + 16, sy + 16))

    Z = 6
    img = Image.new("RGBA", (W * 16, H * 16), (60, 140, 60, 255))
    for r in range(H):
        for c in range(W):
            g = gids[r * W + c]
            if g:
                img.alpha_composite(tile(g), (c * 16, r * 16))
    img.resize((W * 16 * Z, H * 16 * Z), Image.NEAREST).convert("RGB").save(out_png)
    print("wrote", out_png)


if __name__ == "__main__":
    if len(sys.argv) >= 4 and sys.argv[1] == "--demo":
        # --demo <tileset.png> <out.png> [material]
        _demo(sys.argv[2], sys.argv[3], sys.argv[4] if len(sys.argv) > 4 else "dirt_grass")
    else:
        print(__doc__)
