#!/usr/bin/env python3
"""Stamp a build id into an example, so a running ROM can say which build it is.

    python3 scripts/stamp_build.py examples/rap-dojo

Writes `<example>/src/buildid.tish` with a counter that increments on every build plus the wall
time. Wire it as a prebuild step and the number on screen settles the only question that matters
when a fix "doesn't work": is the thing running the thing that was just built?

This exists because that question cost several rounds of debugging. A change was made, the ROM did
not change behaviour, and the possibilities — wrong fix, or stale binary — look identical from the
outside. Guessing between them wasted more time than the bugs did, and guessing WRONG (blaming the
build) is worse than useless. A visible id turns it into something you read off the screen.
"""
import os
import sys
import time

ex = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")
counter = os.path.join(ex, ".buildno")

n = 0
if os.path.isfile(counter):
    try:
        n = int(open(counter).read().strip())
    except ValueError:
        n = 0
n += 1
with open(counter, "w") as f:
    f.write(str(n))

stamp = time.strftime("%H:%M:%S")
out = os.path.join(ex, "src", "buildid.tish")
os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write(
        "// GENERATED by scripts/stamp_build.py on every build. Do not edit, do not commit.\n"
        f'export const BUILD_ID = "b{n} {stamp}"\n'
    )
print(f"build b{n} {stamp}")
